--
-- PostgreSQL database dump
--


-- Dumped from database version 16.12 (Debian 16.12-1.pgdg12+1)
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clubs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clubs (
    id integer NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: clubs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clubs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clubs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clubs_id_seq OWNED BY public.clubs.id;


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    code text NOT NULL,
    name text NOT NULL,
    excluded boolean DEFAULT false
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    distance integer NOT NULL,
    stroke text NOT NULL,
    gender text NOT NULL,
    pool_length integer NOT NULL
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.meets (
    id integer NOT NULL,
    meet_id text,
    name text NOT NULL,
    city text,
    country_code text,
    start_date date,
    end_date date,
    pool_length integer,
    imported_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: meets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.meets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.results (
    id integer NOT NULL,
    swimmer_id integer,
    meet_id integer,
    event_id integer,
    time_seconds numeric(10,2) NOT NULL,
    rank integer,
    heat integer,
    lane integer,
    result_date date,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status text,
    points numeric(10,2),
    qualification text,
    entry_time_seconds numeric(10,2),
    reaction_time text,
    comment text,
    age_group_id text,
    age_group_min integer,
    age_group_max integer,
    age_group_label text,
    age_group_rank integer,
    age_group_order integer,
    event_round character varying(16),
    is_relay boolean DEFAULT false NOT NULL,
    relay_count integer,
    points_fina integer,
    points_rudolph integer,
    CONSTRAINT results_relay_count_check CHECK (((relay_count IS NULL) OR (relay_count > 1)))
);


--
-- Name: COLUMN results.event_round; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.results.event_round IS 'LENEX event round token, e.g. PRE (preliminary), FIN (final), TIM (timed final).';


--
-- Name: COLUMN results.is_relay; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.results.is_relay IS 'True when this athlete result represents a LENEX team relay performance.';


--
-- Name: COLUMN results.relay_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.results.relay_count IS 'Number of legs for a relay result, for example 4 for a 4 x 100 relay.';


--
-- Name: results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: splits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.splits (
    id integer NOT NULL,
    result_id integer,
    distance integer NOT NULL,
    time_seconds numeric(10,2) NOT NULL,
    split_order integer NOT NULL
);


--
-- Name: splits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.splits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.splits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: swimmer_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.swimmer_aliases (
    id integer NOT NULL,
    swimmer_pk integer NOT NULL,
    source_swimmer_id text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    source_country_code text
);


--
-- Name: swimmer_aliases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.swimmer_aliases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.swimmer_aliases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: swimmers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.swimmers (
    id integer NOT NULL,
    swimmer_id text NOT NULL,
    first_name text,
    last_name text,
    birth_year integer NOT NULL,
    gender text,
    country_code text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    club_id integer
);


--
-- Name: swimmers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.swimmers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.swimmers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clubs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs ALTER COLUMN id SET DEFAULT nextval('public.clubs_id_seq'::regclass);


--
-- Name: clubs clubs_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_name_key UNIQUE (name);


--
-- Name: clubs clubs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_pkey PRIMARY KEY (id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (code);


--
-- Name: events events_distance_stroke_gender_pool_length_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_distance_stroke_gender_pool_length_key UNIQUE (distance, stroke, gender, pool_length);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: meets meets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meets
    ADD CONSTRAINT meets_pkey PRIMARY KEY (id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- Name: results results_swimmer_id_meet_id_event_id_heat_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_swimmer_id_meet_id_event_id_heat_key UNIQUE (swimmer_id, meet_id, event_id, heat);


--
-- Name: splits splits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.splits
    ADD CONSTRAINT splits_pkey PRIMARY KEY (id);


--
-- Name: swimmer_aliases swimmer_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmer_aliases
    ADD CONSTRAINT swimmer_aliases_pkey PRIMARY KEY (id);


--
-- Name: swimmers swimmers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmers
    ADD CONSTRAINT swimmers_pkey PRIMARY KEY (id);


--
-- Name: swimmers swimmers_swimmer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmers
    ADD CONSTRAINT swimmers_swimmer_id_key UNIQUE (swimmer_id);


--
-- Name: idx_results_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_results_event ON public.results USING btree (event_id);


--
-- Name: idx_results_swimmer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_results_swimmer ON public.results USING btree (swimmer_id);


--
-- Name: idx_results_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_results_time ON public.results USING btree (time_seconds);


--
-- Name: idx_swimmer_aliases_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_swimmer_aliases_source ON public.swimmer_aliases USING btree (source_country_code, source_swimmer_id);


--
-- Name: idx_swimmer_aliases_swimmer_pk; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_swimmer_aliases_swimmer_pk ON public.swimmer_aliases USING btree (swimmer_pk);


--
-- Name: idx_swimmer_aliases_unique_source; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_swimmer_aliases_unique_source ON public.swimmer_aliases USING btree (source_country_code, source_swimmer_id);


--
-- Name: idx_swimmers_birth_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_swimmers_birth_year ON public.swimmers USING btree (birth_year);


--
-- Name: idx_swimmers_country; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_swimmers_country ON public.swimmers USING btree (country_code);


--
-- Name: results_points_fina_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX results_points_fina_idx ON public.results USING btree (points_fina);


--
-- Name: results_points_rudolph_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX results_points_rudolph_idx ON public.results USING btree (points_rudolph);


--
-- Name: swimmers_club_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX swimmers_club_idx ON public.swimmers USING btree (club_id);


--
-- Name: meets meets_country_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.meets
    ADD CONSTRAINT meets_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code);


--
-- Name: results results_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: results results_meet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_meet_id_fkey FOREIGN KEY (meet_id) REFERENCES public.meets(id);


--
-- Name: results results_swimmer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_swimmer_id_fkey FOREIGN KEY (swimmer_id) REFERENCES public.swimmers(id);


--
-- Name: splits splits_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.splits
    ADD CONSTRAINT splits_result_id_fkey FOREIGN KEY (result_id) REFERENCES public.results(id) ON DELETE CASCADE;


--
-- Name: swimmer_aliases swimmer_aliases_source_country_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmer_aliases
    ADD CONSTRAINT swimmer_aliases_source_country_code_fkey FOREIGN KEY (source_country_code) REFERENCES public.countries(code);


--
-- Name: swimmer_aliases swimmer_aliases_swimmer_pk_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmer_aliases
    ADD CONSTRAINT swimmer_aliases_swimmer_pk_fkey FOREIGN KEY (swimmer_pk) REFERENCES public.swimmers(id) ON DELETE CASCADE;


--
-- Name: swimmers swimmers_club_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.swimmers
    ADD CONSTRAINT swimmers_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--
